insert into marca(nombre, pais) values ('ABARTH', 'China');
insert into marca(nombre, pais) values ('ALFA ROMEO', 'Guatemala');
insert into marca(nombre, pais) values ('ALFA ROMEO (FIAT)', 'Guatemala');
insert into marca(nombre, pais) values ('ASTON MARTIN', 'Estados Unidos');
insert into marca(nombre, pais) values ('AUDI', 'China');
insert into marca(nombre, pais) values ('BENTLEY', 'Guatemala');
insert into marca(nombre, pais) values ('BMW', 'Guatemala');
insert into marca(nombre, pais) values ('BYD', 'Colombia');
insert into marca(nombre, pais) values ('CHEVROLET', 'Guatemala');
insert into marca(nombre, pais) values ('CITROEN', 'Italia');
insert into marca(nombre, pais) values ('DACIA', 'Guatemala');
insert into marca(nombre, pais) values ('DFSK', 'Colombia');
insert into marca(nombre, pais) values ('DS', 'China');
insert into marca(nombre, pais) values ('FERRARI', 'Guatemala');
insert into marca(nombre, pais) values ('FERRARI (FCA)', 'China');
insert into marca(nombre, pais) values ('FIAT', 'Estados Unidos');
insert into marca(nombre, pais) values ('FIAT (FIAT)', 'Venezuela');
insert into marca(nombre, pais) values ('FORD', 'Guatemala');
insert into marca(nombre, pais) values ('HONDA', 'Brazil');
insert into marca(nombre, pais) values ('HYUNDAI', 'Brazil');
insert into marca(nombre, pais) values ('INFINITI', 'Guatemala');
insert into marca(nombre, pais) values ('ISUZU', 'China');
insert into marca(nombre, pais) values ('JAGUAR', 'Estados Unidos');
insert into marca(nombre, pais) values ('JEEP', 'Guatemala');
insert into marca(nombre, pais) values ('JEEP (FIAT)', 'Guatemala');
insert into marca(nombre, pais) values ('KIA', 'Colombia');
insert into marca(nombre, pais) values ('LADA', 'Colombia');
insert into marca(nombre, pais) values ('LAMBORGHINI', 'Guatemala');
insert into marca(nombre, pais) values ('LANCIA', 'Estados Unidos');
insert into marca(nombre, pais) values ('LANCIA (FIAT)', 'Guatemala');
insert into marca(nombre, pais) values ('LAND ROVER', 'Estados Unidos');
insert into marca(nombre, pais) values ('LEXUS', 'Guatemala');
insert into marca(nombre, pais) values ('MAHINDRA', 'Italia');
insert into marca(nombre, pais) values ('MASERATI', 'Guatemala');
insert into marca(nombre, pais) values ('MAZDA', 'China');
insert into marca(nombre, pais) values ('MERCEDES', 'Guatemala');
insert into marca(nombre, pais) values ('MINI', 'Guatemala');
insert into marca(nombre, pais) values ('MITSUBISHI', 'Italia');
insert into marca(nombre, pais) values ('MORGAN', 'Colombia');
insert into marca(nombre, pais) values ('NISSAN', 'Guatemala');
insert into marca(nombre, pais) values ('OPEL', 'Italia');
insert into marca(nombre, pais) values ('PEUGEOT', 'China');
insert into marca(nombre, pais) values ('PORSCHE', 'Guatemala');
insert into marca(nombre, pais) values ('RENAULT', 'Estados Unidos');
insert into marca(nombre, pais) values ('ROLLS-ROYCE', 'Guatemala');
insert into marca(nombre, pais) values ('SEAT', 'China');
insert into marca(nombre, pais) values ('SKODA', 'Brazil');
insert into marca(nombre, pais) values ('SMART', 'Guatemala');
insert into marca(nombre, pais) values ('SSANGYONG', 'Guatemala');
insert into marca(nombre, pais) values ('SUBARU', 'China');
insert into marca(nombre, pais) values ('SUZUKI', 'Guatemala');
insert into marca(nombre, pais) values ('TATA', 'Estados Unidos');
insert into marca(nombre, pais) values ('TESLA', 'Guatemala');
insert into marca(nombre, pais) values ('TOYOTA', 'Guatemala');
insert into marca(nombre, pais) values ('VOLKSWAGEN', 'China');
insert into marca(nombre, pais) values ('VOLVO', 'Colombia');