insert into marca(nombre) values ('ABARTH');
insert into marca(nombre) values ('ALFA ROMEO');
insert into marca(nombre) values ('ALFA ROMEO (FIAT)');
insert into marca(nombre) values ('ASTON MARTIN');
insert into marca(nombre) values ('AUDI');
insert into marca(nombre) values ('BENTLEY');
insert into marca(nombre) values ('BMW');
insert into marca(nombre) values ('BYD');
insert into marca(nombre) values ('CHEVROLET');
insert into marca(nombre) values ('CITROEN');
insert into marca(nombre) values ('DACIA');
insert into marca(nombre) values ('DFSK');
insert into marca(nombre) values ('DS');
insert into marca(nombre) values ('FERRARI');
insert into marca(nombre) values ('FERRARI (FCA)');
insert into marca(nombre) values ('FIAT');
insert into marca(nombre) values ('FIAT (FIAT)');
insert into marca(nombre) values ('FORD');
insert into marca(nombre) values ('HONDA');
insert into marca(nombre) values ('HYUNDAI');
insert into marca(nombre) values ('INFINITI');
insert into marca(nombre) values ('ISUZU');
insert into marca(nombre) values ('JAGUAR');
insert into marca(nombre) values ('JEEP');
insert into marca(nombre) values ('JEEP (FIAT)');
insert into marca(nombre) values ('KIA');
insert into marca(nombre) values ('LADA');
insert into marca(nombre) values ('LAMBORGHINI');
insert into marca(nombre) values ('LANCIA');
insert into marca(nombre) values ('LANCIA (FIAT)');
insert into marca(nombre) values ('LAND ROVER');
insert into marca(nombre) values ('LEXUS');
insert into marca(nombre) values ('MAHINDRA');
insert into marca(nombre) values ('MASERATI');
insert into marca(nombre) values ('MAZDA');
insert into marca(nombre) values ('MERCEDES');
insert into marca(nombre) values ('MINI');
insert into marca(nombre) values ('MITSUBISHI');
insert into marca(nombre) values ('MORGAN');
insert into marca(nombre) values ('NISSAN');
insert into marca(nombre) values ('OPEL');
insert into marca(nombre) values ('PEUGEOT');
insert into marca(nombre) values ('PORSCHE');
insert into marca(nombre) values ('RENAULT');
insert into marca(nombre) values ('ROLLS-ROYCE');
insert into marca(nombre) values ('SEAT');
insert into marca(nombre) values ('SKODA');
insert into marca(nombre) values ('SMART');
insert into marca(nombre) values ('SSANGYONG');
insert into marca(nombre) values ('SUBARU');
insert into marca(nombre) values ('SUZUKI');
insert into marca(nombre) values ('TATA');
insert into marca(nombre) values ('TESLA');
insert into marca(nombre) values ('TOYOTA');
insert into marca(nombre) values ('VOLKSWAGEN');
insert into marca(nombre) values ('VOLVO');